Restored session: Thu Mar 30 14:28:20 CDT 2017
[?1034h$ ls
2016-11-29_17-01-01.jpg
[34m2048[39;49m[0m
ACI-REF_Project.odp
[34mC[39;49m[0m
[34mCloud[39;49m[0m
[35mLauncher.app[39;49m[0m
[34mTC2_C[39;49m[0m
[34mTC3_C[39;49m[0m
Untitled 2.rtf
Untitled.kmz
Untitled.rtf
WirelessDiagnostics_C02PP0UTFVH6_2015-06-10_19.39.06.tar.gz
aci-ref_project.rtf
acronyms.rtf
[34mcacti[39;49m[0m
[34mcolors[39;49m[0m
[34mdc_2016-07-25[39;49m[0m
ford-versypt.rtf
[34mipad[39;49m[0m
[34mpages-test[39;49m[0m
[34mpictures[39;49m[0m
[34mplanets[39;49m[0m
script.pipe
script.txt
setup_ssh_key.sh
[34mshell-2017-03-30[39;49m[0m
[34mshell-transcript[39;49m[0m
[34mswc20151210[39;49m[0m
[34mswc20160314[39;49m[0m
[34mswc_2016-05-23[39;49m[0m
[34mswc_2017-01-03[39;49m[0m
urls.rtf
$ whoami
elinde
$ pwd
/Users/elinde/Desktop
$ date
Thu Mar 30 15:13:05 CDT 2017
$ echo $PROMT[KPT_COMMAND
history 1 | sed 's/^\ *[0-9]\+\ \+//' >> /Users/elinde/Desktop/shell-2017-03-30/commands.txt
$ history 1 | sed 's/^\ *[0-9]\+\ \+//'
  507  history 1 | sed 's/^\ *[0-9]\+\ \+//'
$ history 1 | sed 's/^\ *[0-9]\+\ \+//'[1P[1@2
  507  history 1 | sed 's/^\ *[0-9]\+\ \+//'
  508  history 2 | sed 's/^\ *[0-9]\+\ \+//'
$ history 2 | sed 's/^\ *[0-9]\+\ \+//'[1P
  508  history 2 | sed 's/^\ *[0-9]\+\ \+//'
  509  history 2 | sed 's/^\ *[0-9]+\ \+//'
$ history 2 | sed 's/^\ *[0-9]+\ \+//'[1P[1@[[1@[[1@0[1@-[1@9[1@][1@*[1P
  509  history 2 | sed 's/^\ *[0-9]+\ \+//'
  510  history 2 | sed 's/^\ *[0-9][0-9]*\ \+//'
$ history 2 | sed 's/^\ *[0-9][0-9]*\ \+//'[1P[1P[1P[1P[1P+[C[C[C[C[C[C[C[1@\[C[C[C[C[C[C[C[C[1P[C[C[C[C[C[C[C[C[[C[C[C[C[C[C[C[C[C[Khistory 2 | sed 's/^\ *[0-9][\ \+//'[1@0[1@-[1@9[1@][1@*[C[C[C[C[1P//' //'*//'
history 2 | sed 's/^\ *[0-9][0-9]*\ \+//'
history 2 | sed 's/^\ *[0-9][0-9]*\ \ *//'
$ history 2 | sed 's/^\ *[0-9][0-9]*\ \ *//'[C[C[1P+//'[5P+[C[C[C[C[C[C[C[1@-[1@e[1@ 
  511  history 2 | sed 's/^\ *[0-9][0-9]*\ \ *//'
  512  history 2 | sed -e 's/^\ *[0-9]+\ \+//'
$ history 2 | sed -e 's/^\ *[0-9]+\ \+//'[1@g
  512  history 2 | sed -e 's/^\ *[0-9]+\ \+//'
  513  history 2 | gsed -e 's/^\ *[0-9]+\ \+//'
$ history 2 | gsed -e 's/^\ *[0-9]+\ \+//'[1P[1P[1P
  513  history 2 | gsed -e 's/^\ *[0-9]+\ \+//'
  514  history 2 | gsed 's/^\ *[0-9]+\ \+//'
$ exit
exit
Saving session...
...saving history...truncating history files...
...completed.
Restored session: Thu Mar 30 15:16:16 CDT 2017
[?1034h$ exit
exit
Saving session...
...saving history...truncating history files...
...completed.
Restored session: Thu Mar 30 15:29:55 CDT 2017
[?1034hc02pp0utfvh6:Desktop elinde$ ls
2016-11-29_17-01-01.jpg
[34m2048[39;49m[0m
ACI-REF_Project.odp
[34mC[39;49m[0m
[34mCloud[39;49m[0m
[35mLauncher.app[39;49m[0m
[34mTC2_C[39;49m[0m
[34mTC3_C[39;49m[0m
Untitled 2.rtf
Untitled.kmz
Untitled.rtf
WirelessDiagnostics_C02PP0UTFVH6_2015-06-10_19.39.06.tar.gz
aci-ref_project.rtf
acronyms.rtf
[34mcacti[39;49m[0m
[34mcolors[39;49m[0m
[34mdc_2016-07-25[39;49m[0m
ford-versypt.rtf
[34mipad[39;49m[0m
[34mpages-test[39;49m[0m
[34mpictures[39;49m[0m
[34mplanets[39;49m[0m
script.pipe
script.txt
setup_ssh_key.sh
[34mshell-2017-03-30[39;49m[0m
[34mshell-transcript[39;49m[0m
[34mswc20151210[39;49m[0m
[34mswc20160314[39;49m[0m
[34mswc_2016-05-23[39;49m[0m
[34mswc_2017-01-03[39;49m[0m
urls.rtf
c02pp0utfvh6:Desktop elinde$ w[Kpwd
/Users/elinde/Desktop
c02pp0utfvh6:Desktop elinde$ whoami
elinde
c02pp0utfvh6:Desktop elinde$ date
Thu Mar 30 15:31:02 CDT 2017
c02pp0utfvh6:Desktop elinde$ tail shell-2017-03-30/full_terminal.html 
c02pp0utfvh6:Desktop elinde$ pwd                                                            
/Users/elinde/Desktop
c02pp0utfvh6:Desktop elinde$ whoami
elinde
c02pp0utfvh6:Desktop elinde$ date
Thu Mar 30 15:31:02 CDT 2017
c02pp0utfvh6:Desktop elinde$ tail s
</pre>
</body>
</html>
c02pp0utfvh6:Desktop elinde$ exit
exit
Saving session...
...saving history...truncating history files...
...completed.
Script started on Thu 30 Mar 2017 03:58:38 PM CDT
$ ls
[0m[01;32mansi2html.sh[0m  full_terminal.html    make_html.sh      short_prompt.bashrc
[01;32mauto_push.sh[0m  full_terminal.script  readme.md         start_transcript.sh
commands.txt  index.html            setup_ssh_key.sh  transcript.bashrc
$ uname -a
Linux 30YVT12 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ exit
exit
Script started on Thu 30 Mar 2017 04:00:12 PM CDT
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ pwd
/home/elinde/shell-2017-03-30
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ whoami
elinde
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ ls -F
[0m[01;32mansi2html.sh[0m*  full_terminal.html    make_html.sh      short_prompt.bashrc
[01;32mauto_push.sh[0m*  full_terminal.script  readme.md         start_transcript.sh
commands.txt   index.html            setup_ssh_key.sh  transcript.bashrc
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ ls -lh
total 88K
-rwxrwxr-x 1 elinde elinde  17K Mar 30 15:58 [0m[01;32mansi2html.sh[0m
-rwxrwxr-x 1 elinde elinde  343 Mar 30 15:58 [01;32mauto_push.sh[0m
-rw-rw-r-- 1 elinde elinde  570 Mar 30 16:00 commands.txt
-rw-rw-r-- 1 elinde elinde  23K Mar 30 16:00 full_terminal.html
-rw-rw-r-- 1 elinde elinde 5.5K Mar 30 16:00 full_terminal.script
-rw-rw-r-- 1 elinde elinde 1.2K Mar 30 15:58 index.html
-rw-rw-r-- 1 elinde elinde 1.3K Mar 30 15:58 make_html.sh
-rw-rw-r-- 1 elinde elinde 3.6K Mar 30 15:58 readme.md
-rw-rw-r-- 1 elinde elinde  659 Mar 30 15:58 setup_ssh_key.sh
-rw-rw-r-- 1 elinde elinde  441 Mar 30 15:58 short_prompt.bashrc
-rw-rw-r-- 1 elinde elinde 2.2K Mar 30 15:58 start_transcript.sh
-rw-rw-r-- 1 elinde elinde  709 Mar 30 15:58 transcript.bashrc
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ date
Thu Mar 30 16:00:35 CDT 2017
]0;elinde@30YVT12: ~/shell-2017-03-30elinde@30YVT12:~/shell-2017-03-30$ 